name: Windows 10
 
on: 
  workflow_dispatch:
 
jobs:
  win10:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0

      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          git clone https://github.com/dockur/windows.git 
          wget -O loop.sh https://github.com/Efebey2903/Docker-VNC/raw/main/loop.sh
          wget -O docker-compose.yml https://raw.githubusercontent.com/Efebey2903/Docker-VNC/main/win10_compose.yml
          sleep 1
          docker-compose build
          sleep 2
          docker-compose up 
          cat compose
          sh loop.sh
